### ISSUE TITLE
Internal Credit System

### ISSUE THREAD

**Issue by Jon-Cavaliere** [codi-hacks/space-race#39]
Add a credit system for unlocking maps and ships.

**Comment by SuperShadowPlay** [comment]
Currently there is no way to "win", so I'll be implementing a way to save credits (and save a spot for times on maps) to lay the groundwork for this to be fully implemented later.

**Comment by SuperShadowPlay** [comment]
- [x] Better or worse times (relative to whatever the average time for that map is) earn more or less credits.
- [ ] Players can wager more credits to increase payout and risk.
