### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by SuperShadowPlay** [codi-hacks/space-race#6]
A main menu that shows up when you first boot the game.

**Comment by jaythomas** [comment]
Prior art for some ideas: https://github.com/jaythomas/love-experiment/blob/master/src/services/menu.lua

**Comment by SuperShadowPlay** [comment]
![Whiteboard 1 -01](https://user-images.githubusercontent.com/42284150/150210329-5b9a034b-97f9-4b44-be20-070f6fd37aa4.png)
