### ISSUE TITLE
Render Culling

### ISSUE THREAD

**Issue by SuperShadowPlay** [codi-hacks/space-race#67]
Currently everything is rendered at all times. Once the maps get bigger (and possibly animated), this will take up a lot of unnecessary resources. We need some sort of service that stops the drawing of objects that are off-screen.

**Comment by wyatt-herkamp** [comment]
I am curious of doing this. I should be able to take a stab this weekend.

**Comment by Jon-Cavaliere** [comment]
My suggestion would be something like a render service that we give renderables too, it then checks if the draw coordinates are outside the camera bounds before drawing.

**Comment by wyatt-herkamp** [comment]
> I am curious of doing this. I should be able to take a stab this weekend.

My attempt resulted in slower rendering and stuff not rendering.
