### ISSUE TITLE
Add more textures

### ISSUE THREAD

**Issue by SuperShadowPlay** [codi-hacks/space-race#9]
Currently the only textured entity is the spaceship itself. Texture all the things!

**Comment by jaythomas** [comment]
This is a very vague description. Every entity we have so far is textured aside from the wall blocks I added to the no_planets level. Perhaps we need more boundary textures so we can build track paths?

**Comment by SuperShadowPlay** [comment]
This was written back when the game was very early on in development, but I'd interpret this as needing to make (decent) textures for the ships (already taken care of by @Broke-Code ), and the (possibly different types of) planets. Some boundary textures would also be appreciated.

**Comment by jaythomas** [comment]
Superseded by #35
